Repository syuaweu/OOPL_CandyCrush, pull requests merged in 2024-06, with the labels that each got.

#1 Reconstruct by rita
  Resources/candy_maps/1.txt
  Resources/candy_maps/11.txt
  Resources/candy_maps/12.txt
  Resources/candy_maps/13.txt
  Resources/candy_maps/14.txt
  Resources/candy_maps/15.txt
  Resources/candy_maps/16.txt
  Resources/candy_maps/17.txt
  Resources/candy_maps/2.txt
  Resources/candy_maps/3.txt
  Resources/candy_maps/4.txt
  Resources/candy_maps/5.txt
  Resources/candy_maps/6.txt
  Resources/candy_maps/7.txt
  Resources/ice_maps/1.txt
  Resources/ice_maps/11.txt
  Resources/ice_maps/12.txt
  Resources/ice_maps/13.txt
  Resources/ice_maps/14.txt
  Resources/ice_maps/15.txt
  Resources/ice_maps/16.txt
  Resources/ice_maps/17.txt
  Resources/ice_maps/2.txt
  Resources/ice_maps/3.txt
  Resources/ice_maps/4.txt
  Resources/ice_maps/5.txt
  Resources/ice_maps/6.txt
  Resources/ice_maps/7.txt
  Resources/init_map/1.txt
  Resources/init_map/11.txt
  Resources/init_map/12.txt
  Resources/init_map/13.txt
  Resources/init_map/14.txt
  Resources/init_map/15.txt
  Resources/init_map/16.txt
  Resources/init_map/17.txt
  Resources/init_map/2.txt
  Resources/init_map/3.txt
  Resources/init_map/4.txt
  Resources/init_map/5.txt
  Resources/init_map/6.txt
  Resources/init_map/7.txt
  Resources/init_map/choose_level.txt
  Resources/map/choose_level.txt
  Source/Game/Candy.cpp
  Source/Game/Candy.h
  Source/Game/Ice.h
  Source/Game/Map.cpp
  Source/Game/Map.h
Labels: enhancement

#3 Reconstruct by rita
  Source/Game/Candy.h
  Source/Game/Map.cpp
  Source/Game/Map.h
  Source/Game/mygame_initialize.cpp
  Source/Game/mygame_run.cpp
Labels: enhancement

#7 fix bug
  Resources/init_map/choose_level.txt
  Source/Game/mygame_run.cpp
Labels: bug

#8 merge
  Resources/candy_maps/1.txt
  Resources/map/choose_level.txt
  Source/Game/Map.cpp
  Source/Game/Map.h
  Source/Game/WinRule.cpp
  Source/Game/WinRule.h
  Source/Game/mygame.h
  Source/Game/mygame_run.cpp
Labels: documentation

#10 special candy
  Resources/candy_maps/1.txt
  Resources/map/choose_level.txt
  Source/Game/Candy.cpp
  Source/Game/Candy.h
  Source/Game/Map.cpp
  Source/Game/mygame_run.cpp
Labels: enhancement

#11 fix fall bug
  Source/Game/Candy.cpp
  Source/Game/Candy.h
  Source/Game/Map.cpp
Labels: bug

#17 dragon and obstacle
  Resources/ice_maps/8.txt
  Resources/init_map/choose_level.txt
  Resources/texture_pack_original/ice/blank.bmp
  Resources/texture_pack_original/surface/blank.bmp
  Resources/win_or_loose.txt
  Source/Game/Map.cpp
  Source/Game/Map.h
  Source/Game/mygame_initialize.cpp
  Source/Game/mygame_run.cpp
Labels: bug
